### ISSUE TITLE
Issues with transparent images that use black text color

### ISSUE THREAD

**Issue by Rava77** [JustOff/advanced-night-mode#9]
Hi, usually advanced-night-mode works fine, but not with svg graphics, like the ones wikipedia uses. System x86-64 Linux, Palemoon 28.4.0
When the graphics has black text or black lines or other stuff drawn with the colour black, advanced-night-mode sets the background colour to black (as it should) but the svg drawn text or image colour black is left as it is, so we have black on black.
Only different colours are visible. Example:
E.g. this svg https://de.wikipedia.org/wiki/Datei:Aliasing_mrtz.svg with advanced-night-mode only shows the large red sinus like graph, but the rest, like the smaller / narrower black sinus graphs and all the other details are unseen cause they are black on black.
"Invert" also not works, only switching advanced-night-mode off for all de.wikipedia (or en.wikipedia…) pages works, but that also means bright white background that I try to avoid.

**Comment by JustOff** [comment]
Unfortunately, this problem is always observed with transparent images that use black text color and there is no general solution.

As a workaround, you can add the following rule to [userContent.css](http://kb.mozillazine.org/UserContent.css):

```css
@-moz-document domain("wikipedia.org") {
  .fullImageLink a img {
    background: lightskyblue !important;
  }
}
```

**Comment by Rava77** [comment]
Thanks, your fix works like a charm.
Unfortunately, _background: lightskyblue_ is quite light (well, it is in the _name of the colour_), do you know of a way previewing different _background: colour_ vs black text without having to restart PM every time?

**Comment by JustOff** [comment]
You can try a less strict selector:

```css
@-moz-document domain("wikipedia.org") {
  a img {
    background: lightskyblue !important;
  }
}
```
